### RunWithDefaultPort
GET http://127.0.0.1:8081/


### PathParam
GET http://127.0.0.1:8080/user/ivfzhou/


### QueryParam
GET http://127.0.0.1:8080/?name=1&name=2


### MultipartAndUrlencodedParam
POST http://127.0.0.1:8080/
Content-Type: application/x-www-form-urlencoded

name[a]=b


### MultipartFile
POST http://127.0.0.1:8080/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="tmp.txt"
Content-Type: text/plain

< ./gin.http
--WebAppBoundary--


### MultipartFiles
POST http://127.0.0.1:8080/
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="tmp1.txt"
Content-Type: text/plain

< ./gin.http

--WebAppBoundary
Content-Disposition: form-data; name="file1"; filename="tmp2.txt"
Content-Type: text/plain

< ./gin.go
--WebAppBoundary--


### GroupRoute
GET 127.0.0.1:8080/v1/


### Log
GET 127.0.0.1:8080/ping


### Bind
POST 127.0.0.1:8080/asd
Content-Type: application/x-www-form-urlencoded

books[a]=b&age=18


### CustomBind
GET http://127.0.0.1:8080/?name=ivfzhou


### Render
GET 127.0.0.1:8080/?callback=fn


### ServeFile
GET 127.0.0.1:8080/gin/gin.http


### ServeHTML
GET 127.0.0.1:8080/


### Redirect
# @no-redirect
POST 127.0.0.1:8080/handle


### BasicAuth
GET http://ivfzhou:123456@127.0.0.1:8080/


### CopyCtx
GET http://127.0.0.1:8080/


### RunTLS
GET https://localhost/


### TmplInBin
GET http://127.0.0.1:8080/
